config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :users do |users|
    post :approve 
    post :reject
    post :remove
    post :request_friendship
  end

  resource :search do
    post :all
  end

  resources :events do |events|
    post :join
    post :leave
    resources :messages, only: [:show, :new, :create, :destroy]
  end
  
  resources :user_sessions
  resources :participations
  
  get 'login' => 'user_sessions#new', as: 'login'
  get 'logout' => 'user_sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :username, uniqueness: true

  # added validation true for image
  # validates :image, presence: true

  has_many :friendships, :dependent => :destroy

  # has_many :friends, :through => :friendships, class_name: "User"

  def friends
    friendships.where(accepted: true).map(&:friend)
  end

  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  
  has_many :participations
  has_many :participated_events, through: :participations, source: :event
  
  mount_uploader :image, UserImageUploader

  has_many :messages
  has_many :events, through: :messages

  # %w[accepted requested pending].each do |status|
  #   define_method("#{status}_friends") do
  #     friendships.where(status: status).map(&:friend)
  #   end
  # end

  # def incoming
  #   Friendship.where(friend: self)
  # end

  # def outgoing
  #   Friendship.where(user: self)
  # end


  #--------------------
  # friend stuff
  #--------------------

  def outgoing_friend_requests
    # outgoing.select {|f| not incoming.include?(f) }
    # me -> someone
    friendships.where(accepted: false)
  end

  def incoming_friend_requests
    # me <- someone
    Friendship.where(friend: self, accepted: false)
  end

  def request_friendship!(friend)
    Friendship.create(user: self, friend: friend, accepted: false)
  end

  def accept_friendship!(friend)
    # f = Friendship.find_by(user: friend, friend: self)
    f = incoming_friend_requests.find_by(user: friend)
    f.accepted = true
    f.save!

    Friendship.create(user: self, friend: friend, accepted: true)
  end

  def deny_friendship!(friend)
    f = incoming_friend_requests.find_by(user: friend)
    f.destroy
  end

  def already_requested?(other)
    !!outgoing_friend_requests.find_by(friend: other)
  end

  def friends?(other)
    friends.include? other
  end

  def destroy_participations(enemy)
    self.participated_events
      .where(creator_id: enemy.id)
      .map{|event| Participation.where(event_id: event.id, user_id: self.id) }
      .flatten
      .map{|event| event.destroy; event.save}
  end

  #--------------------
  # event stuff
  #--------------------

  def participate_in!(event)
    event.participation.create(user: self)
  end

  def un_participate_in!(event)
    event.participation.find_by(user: self).destroy
    # f.destroy
  end

  #--------------------
  # junk drawer
  #--------------------


  # Warning: This is for admin use
  def enfriend!(friend)
    friendships.create(friend: friend)
    friend.friendships.create(friend: self)
  end

  def unfriend!(enemy)
    friendships.find_by(friend: enemy).destroy
    enemy.friendships.find_by(friend: self).destroy
  end

  def inspect
    "<User #{id}: #{first_name} #{last_name} (#{email})>"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in, except: [:create, :new]
  def index
    @f = current_user.friends
    @ifr = current_user.incoming_friend_requests.map(&:user)
    @ofr = current_user.outgoing_friend_requests.map(&:friend)
    @nf = User.all - @f - @ifr - @ofr - [current_user]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to events_url, {notice: "Signed up!"}
    else
      # flash.now[:alert] = "Error: could not complete the request."
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def show
    @users = User.all - [current_user]
    @user = User.find(params[:id])
  end

  def edit 
  end

  def destroy
  end

  def remove
    friend = User.find(params[:user_id])
    current_user.unfriend!(friend)
    redirect_to users_path
  end

  def approve
    friend = User.find(params[:user_id])
    current_user.accept_friendship!(friend)
    redirect_to users_path
  end

  def reject
    friend = User.find(params[:user_id])
    current_user.deny_friendship!(friend)
    redirect_to users_path
  end

  def request_friendship
    friend = User.find(params[:user_id])
    current_user.request_friendship!(friend)
    redirect_to users_path
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :username, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_events_search.html.erb
<form class="navbar-form navbar-right" role="search">
  <div class="form-group">
		<%= form_tag events_path, method: :get, authentication: false, id: 'search-form' do %>
			<%= text_field_tag :search, params[:params], :input_type =>'text', :class => 'form-control', :placeholder =>'search' %>
			<%= submit_tag "Search", :type => 'submit', :class => 'btn btn-default thin form-control' %>
		<% end %>
  </div>
</form><br> 

app/views/users/_form.html.erb
<div id="fullscreen_bg_cups" class="fullscreen_bg_cups"/>

  <div id="signup-logos"></div>
  <div class="transparent-bg">
  <div class="form-signup">
    <h3 class="Signin-page-heading">CREATE AN ACCOUNT.</h3>
    <hr class="Signin-page-line">
  <% if !@user.errors.messages.blank? %> 
    <% @user.errors.full_messages.each do |message| %>
      <div class="alert">
        <%= message %><br/>
      </div>
    <% end %>
  <% end %><br/>

  <%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
    </div>
    
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
    </div>
    
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
    </div>
    
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
    </div>
    
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password' %>
    </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div><br />

    <div class="field">
      <%= f.submit "Submit", class: 'btn btn-lg btn-primary btn-block' %>
    </div><br>
  <% end %>
  <%= link_to "Login", login_path %>
  </div>
</div>
</div>

app/views/users/_my_friends.html.erb
<% if @user == current_user %> 
<h1>My Friends</h1>
		<ul>
			<% current_user.friends.each do |user| %>
					<li><%= link_to user.first_name, user_path(user) %></li>
			<% end %>
			<p>Number of Friends: <%= current_user.friends.count %> </p>
		</ul>
<% end %>

app/views/users/_user.html.erb
<div>
	<h3><%= link_to user.username, user_path(user) %></h3>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1 class="main-heading">FRIENDS.</h1>
<!-- <hr> -->

<div class="item-section bottom-space">
	<div class="item-label">Friends</div>		
	<div class="item-info friends">
		<div class="user-content">
			<% if @f.empty? %>
				<p>You have no friends yet</p>
			<% else %>	
				<% @f.each do |user| %>
					<div class="user-row">
						<%= link_to user.username, user_path(user) %>
						<%= link_to user_remove_path(user), method: :post, class: "user-action" do %>
							<i class="glyphicon glyphicon-minus-sign"></i>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<div class="item-section bottom-space">
	<div class="item-label">Incoming Requests</div>		
	<div class="item-info friends">
		<div class="user-content">
			<% if @ifr.empty? %>
				<p>No pending requests</p>
			<% else %>	
				<% @ifr.each do |user| %>
					<div class="user-row">
						<%= link_to user.username, user_path(user) %> 
						<%= link_to user_approve_path(user), method: :post, class: "user-action" do %>
							<i class="glyphicon glyphicon-plus-sign"></i>
						<% end %>
						<%= link_to user_reject_path(user), method: :post, class: "user-action" do %>
							<i class="glyphicon glyphicon-remove-sign"></i>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<div class="item-section bottom-space">
	<div class="item-label">Sent Requests</div>		
	<div class="item-info friends">
		<div class="user-content">
			<% if @ofr.empty? %>
				<p>No pending requests</p>
			<% else %>
				<% @ofr.each do |user| %>
					<div class="user-row"><%= link_to user.username, user_path(user) %></div> 
					<i class="glyphicon glyphicon-send"></i>
				<% end %> 
			<% end %>
		</div>
	</div>
</div>

<div class="item-section bottom-space">
	<div class="item-label">Strangers</div>
	<div class="item-info friends">
		<div class="user-content">
			<% if @nf.empty? %>
				<p>There is no one else to friend</p>
			<% else %>		
				<% @nf.each do |user| %>
					<div class="user-row">
						<%= link_to user.username, user_path(user) %> 
						<%= link_to user_request_friendship_path(user), method: :post, class: "user-action" do %>
							<i class="glyphicon glyphicon-plus-sign"></i>
						<% end %>
					</div>
				<% end %> 
			<% end %>
		</div>
	</div>
</div>


	

app/views/users/new.html.erb
<h1>New User</h1>

<div class="new-user-form">
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="profile-background ">

  <div class="profile-photo">
    <%= image_tag @user.image_url %>
    <% if @user == current_user %>  
    <% end %>
  </div>

  <h1 class="main-heading centered"><%= @user.username %>
    <%# unless @user = current_user %>
      <% if current_user.friends?(@user)  %>
        <!-- <p class="status-right-justified">You are friends</p> -->
        <i class="glyphicon glyphicon-ok-sign left-action green-icon"></i>

      <% elsif current_user.already_requested?(@user) %>
        <p class="status-right-justified">Request Sent</p>
      <% else %>
      <!-- ++++++++ ADD BUTTON ++++++++ -->
        <%= link_to user_request_friendship_path(@user), method: :post, class: "user-action left-action" do %>
          <i class="glyphicon glyphicon-plus-sign"></i>
        <% end %>
      <!-- ++++++++ ADD BUTTON ++++++++ -->
      <% end %>
    <%# end %>
  </h1>
  <!-- </div> -->
</div>

<!-- <div class="command-center">
  
</div> -->


<!-- <hr> -->

<div class="command-center">
  <div class="inner-command-left">
    <div class="top-inner">
      <h2 class="inner-command-label">FRIENDS</h2>
    </div>
    <div class="bottom-inner">
      <h1 class="command-number"><%= @user.friends.count %></h1>
    </div>
  </div>

  <div class="inner-command-center">
    <div class="top-inner">
      <h2 class="inner-command-label">EVENTS</h2>
    </div>
    <div class="bottom-inner">
      <h1 class="command-number"><%= @user.created_events.count %></h1>
    </div>
  </div>
  <div class="inner-command-right">
    <div class="top-inner">
      <h2 class="inner-command-label">SCORE</h2>
    </div>
    <div class="bottom-inner">
      <h1 class="command-number">
        <%=((@user.created_events.count)*200)+((@user.participated_events.count)*125)+((@user.friends.count)*75)%>
      </h1>
    </div>
  </div>
</div>

<div class="all-items">
  <div class="item-section">
    <div class="item-label">Created events</div>
    <div class="item-info friends">
      <% if @user.created_events.empty? %>
        You have not created an event yet
      <% else %>
        <% @user.created_events.each do |event| %>
          <div>
            <%= link_to event.event_name, event_path(event) %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="item-section">
    <div class="item-label">Joined events</div>
    <div class="item-info friends">
      <% if @user.participated_events.empty? %>
        You have not joined an event yet
      <% else %>
        <% @user.participated_events.each do |event| %>
          <div>
            <%= link_to event.event_name, event_path(event) %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

<!-- Only shows 'Add Friend' button if: you aren't already friends or you havent already requested to be friends.  -->
  <%# if @user == !(current_user || current_user.request_friendship!(@user) || current_user.friends?(@user)) %>
    
    <%# form_for(:friendship, :url => user_friends_path(:user_id => current_user.id, :friend_id => @user.id)) do |f| %>
      <%#= submit_tag "Add to My Friends" %>
    <%# end %>
  <%# end %>
<%# end %>

  <% if @user == current_user %>
    <div class="item-section">
      <div class="item-label">Friends</div>
      <div class="item-info friends">
        <% if @user.friends.empty? %>
          You do not have any friends yet
        <% else %>
          <% @user.friends.each do |friend| %>
              <div>
              <%= link_to friend.username, user_path(friend) %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>  
<% end %>