config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :users do |users|
    post :approve 
    post :reject
    post :remove
    post :request_friendship
  end

  resource :search do
    post :all
  end

  resources :events do |events|
    post :join
    post :leave
    resources :messages, only: [:show, :new, :create, :destroy]
  end
  
  resources :user_sessions
  resources :participations
  
  get 'login' => 'user_sessions#new', as: 'login'
  get 'logout' => 'user_sessions#destroy', as: 'logout'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :messages
  has_many :users, through: :messages
  
  validates :event_name, presence: true
  validates :description, presence: true
  validates :event_datetime, presence: true
  validates :event_name, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :participation
  has_many :participants, through: :participation, source: :user

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :ensure_logged_in

  def index
    @friends_events = current_user.friends.map(&:created_events).flatten
    @created_events = current_user.created_events
    if params[:search]
      @friends_events = Event.where("id in (?) AND LOWER(event_name) LIKE LOWER(?)", @friends_events.map(&:id), "%#{params[:search]}%")
      @created_events = Event.where("id in (?) AND LOWER(event_name) LIKE LOWER(?)", @created_events.map(&:id), "%#{params[:search]}%")
    end
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
  end


  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    if @event.save
      redirect_to events_url(@event.id)
    else 
      render :new
    end
  end

  def join
    event = Event.find(params[:event_id])
    current_user.participate_in!(event)
    redirect_to current_user
  end

  def leave
    event = Event.find(params[:event_id])
    current_user.un_participate_in!(event)
    redirect_to current_user
  end

  def show
    @event = Event.find(params[:id])

    if current_user
      @message = @event.messages.build
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

private
  def event_params
    params.require(:event).permit(:event_name, :description, :event_datetime, :location, :url, :creator_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div>
	<h3><%= link_to event.event_name, event_path(event) %></h3>
</div>

app/views/events/_events_search.html.erb
<form class="navbar-form navbar-right" role="search">
  <div class="form-group">
		<%= form_tag events_path, method: :get, authentication: false, id: 'search-form' do %>
			<%= text_field_tag :search, params[:params], :input_type =>'text', :class => 'form-control', :placeholder =>'search' %>
			<%= submit_tag "Search", :type => 'submit', :class => 'btn btn-default thin form-control' %>
		<% end %>
  </div>
</form><br> 

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1 class="main-heading">Events.</h1>
<hr>
<%#= render :partial => 'events_search' %>

<%= link_to new_event_path, class: 'btn btn-lg btn-primary btn-block on-white' do %>
	<span class="glyphicon glyphicon-plus"></span> CREATE A NEW EVENT 
<% end %>

<% if (@created_events.count + @friends_events.count) == 0 %>
  <br><h3 class="no-events-yet">No events yet... why don't you get the ball rolling?</h3>
<% else %>

	<%#= link_to "Create a new Event!", new_event_path, class: 'btn btn-lg btn-primary btn-block on-white' %>

	<!-- Below must be tested -->
	<div class="item-section">
		<div class="item-label">My events</div>
		<% @created_events.each do |event| %>
			<!-- FLIPPING CONTAINER -->
			<div class="vertical-flip-container flip-container floatR" ontouchstart="this.classList.toggle('hover');">
			  <div class="flipper">
			    <div class="front">
			      <!-- The front face -->
						<h3><%= link_to event.event_name, event_path(event), class: "event-list-titles-dark" %></h3>
			    </div>


			    <div class="back">
			       <!-- The back face -->
			      <h3><%= link_to event.event_name, event_path(event), class: "event-list-titles-light" %></h3>
			      <hr class="event-index-card-lines">
						<p class="event-description"><%= event.description.truncate(200) %></p><br />
			    </div>


			  	<div class="clear"></div>
				</div>
			</div>
			<div class="clear"></div><br>
			<!-- FLIPPING CONTAINER -->
		<% end %>
	</div>

 <br>
	<div class="item-section">
		<div class="item-label">Friend events</div>
		<% @friends_events.each do |event| %>
				
				<!-- FLIPPING CONTAINER -->
			<div class="vertical-flip-container flip-container floatR" ontouchstart="this.classList.toggle('hover');">
			  <div class="flipper">
			    <div class="front">
			      <!-- The front face -->
						<h3><%= link_to event.event_name, event_path(event), class: "event-list-titles-dark" %></h3>
			    </div>
			    <div class="back">
			       <!-- The back face -->
			      <h3><%= link_to event.event_name, event_path(event), class: "event-list-titles-light" %></h3>
			      <hr class="event-index-card-lines">
						<p class="event-description"><%= event.description.truncate(200) %></p><br />
			    </div>
			  	<div class="clear"></div>
				</div>
			</div>
			<div class="clear"></div><br>
			<!-- FLIPPING CONTAINER -->
		<% end %>
	</div>
<% end %>

app/views/events/new.html.erb
<h1 class="main-heading">Create.</h1>
<hr><br>
<%= form_for (@event) do |f| %>
	<div class="field">
		<%= f.label :event_name, class: 'white-background' %><br />
		<%= f.text_field :event_name, class: 'form-control', placeholder: "What've you never done?" %>
	</div><br />

	<div class="field">
		<%= f.label :description, class: 'white-background' %><br />
		<%= f.text_area :description, class: 'form-control', placeholder: "Ex. Why haven't you done this yet?" %>
	</div><br />

	<div class="field">
		<%= f.label :event_datetime, class: 'white-background' %><br />
		<%= f.datetime_select :event_datetime,  class: 'datetime-buttons', placeholder: 'Date & Time' %>
	</div><br />

	<div class="field">
		<%= f.label :location, class: 'white-background' %><br />
		<%= f.text_field :location, class: 'form-control', placeholder: "Where's this happnin'?" %>
	</div><br />

	<div class="field">
		<%= f.label :url, class: 'white-background' %><br />
		<%= f.text_field :url,  class: 'form-control ', placeholder: 'Optional' %>
	</div><br><br><br>
	
	<div id="sumbit">
		<%= f.submit "Submit", class: 'btn btn-lg btn-primary btn-block on-white' %>
	</div>
<% end %> 

app/views/events/show.html.erb
<!-- Page is in a large if statement that will only show the event page if you are friends with that user. If you aren't friends with that user then it says 404 not found. -->
<% if @friends_events = current_user.friends.map(&:created_events).flatten.include?(@event) || current_user.created_events.flatten.include?(@event) %>
<div class="white-backer">
  <div class="event-header">
    <h3 class="event-title"><%= @event.event_name %></h3>
    <div class="byline"><%= link_to @event.creator.first_name, user_path(@event.creator) %>
    </div>
  </div>
</div>
<div class="top-space"></div>
<div class="item-section">
  <div class="item-label">description</div>
  <div class="item-info">
    <p><%= @event.description %></p>
  </div>
</div>

<div class="item-section">
  <div class="item-label">time</div>
  <div class="item-info">
    <p><%= @event.event_datetime.strftime("%d %b. %Y %H:%M") %></p>
  </div>
</div>

<div class="item-section">
  <div class="item-label">location</div>
  <div class="item-info">
    <p><%= @event.location %></p>
  </div>
</div>

<div class="item-section">
  <div class="item-info">
     <i class="fa fa-external-link"></i> <%= link_to "website", "http://#{@event.url}" %>
  </div>
</div>
    
<!-- If the user created the event, show the delete button, or else if the user isnt participating in the event show the join button, or if they are show the you are attending note -->
<% if @event.creator == current_user %> 
  <%= button_to "Delete Event", event_path(@event), {method: :delete, class: 'btn btn-default thin form-control event-button event-action delete-message'} %>
<% elsif %>
  <% if !current_user.participated_events.include?(@event) %>
    <%= button_to "Join Event", event_join_path(@event), method: :post, class: 'btn btn-default thin form-control event-button event-action delete-message'  %>
  <% elsif %>
    <%= button_to "Leave Event", event_leave_path(@event), method: :post, class: 'btn btn-default thin form-control event-button event-action delete-message'  %>
    <h3 class="event-attendance"> You are attending this event!</h3>
  <% end %>
<% end %>


<!-- ++++++++++Conversation Portion++++++++++ -->
<% if current_user %>
<div id="event-list">
 <%= render @event.messages %>
</div>
<% end %>



<!-- ++++++++++++++++++++++++++++++++++++++++ -->
<%= form_for([@event, @message], remote: true) do |f| %>
<div id="message-errors">
  <% if @message.errors.any? %>
  <%= render partial: 'message/message_form_errors' %>
  <% end %>
</div>

<div class="field">
<h4 class="text-form-heading">Speak your mind.</h4>
  <%= f.text_area :body %>
</div><br>

<div class="actions">
  <%= f.submit 'Send Message', class: 'btn btn-default thin form-control event-button create-message'%>
</div>
<% end %>

<% else %>
<div class="lost-box">
  <h1 class="not-found">Nothing to see here... <br>Move along.</h1>
</div>
<% end %>