config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :users do |users|
    post :approve 
    post :reject
    post :remove
    post :request_friendship
  end

  resource :search do
    post :all
  end

  resources :events do |events|
    post :join
    post :leave
    resources :messages, only: [:show, :new, :create, :destroy]
  end
  
  resources :user_sessions
  resources :participations
  
  get 'login' => 'user_sessions#new', as: 'login'
  get 'logout' => 'user_sessions#destroy', as: 'logout'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    if @user = login(params[:username], params[:password], params[:remember_me])
      redirect_to(root_url)
    else
      flash.now[:alert] = "Login failed!"
      render "new"
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<!-- <div id="fullscreen_bg" class="fullscreen_bg"/> -->
<!-- ^^BEACH FUN IMAGE^^ -->
<div id="fullscreen_bg_cups" class="fullscreen_bg_cups"/>

<div id="signup-logos"></div>


<div class="signin-logo1"></div>
  <div class="transparent-bg">
    <div class="form-signin">
      
      <h3 class="Signin-page-heading">LOGIN.</h3>
      <!-- <hr class="Signin-page-line"> -->
      <!-- <h2>Log in</h2> -->
      <%= form_tag user_sessions_path, :method => :post do %>
        <div>
          <%= label_tag :username %><br />
          <%= text_field_tag :username, params[:username], class: 'form-control', placeholder: 'Username' %>
        </div>

        <div class="field">
          <%= label_tag :password %><br />
          <%= password_field_tag :password, params[:password], class: 'form-control', placeholder: 'password' %>
        </div>

        <div class="field">
          <%= check_box_tag :remember_me %>
          <%= label_tag :remember_me, params[:remember_me],  class: "checkbox" %>
        </div><br>

        <div class="actions">
          <%= submit_tag "Login", class: 'btn btn-lg btn-primary btn-block' %>
        </div><br />
      <% end %>

      <%= link_to "Sign up", new_user_path %>


      </div>
    <div class="login-container">
    </div>
  </div>
</div>