config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :users do |users|
    post :approve 
    post :reject
    post :remove
    post :request_friendship
  end

  resource :search do
    post :all
  end

  resources :events do |events|
    post :join
    post :leave
    resources :messages, only: [:show, :new, :create, :destroy]
  end
  
  resources :user_sessions
  resources :participations
  
  get 'login' => 'user_sessions#new', as: 'login'
  get 'logout' => 'user_sessions#destroy', as: 'logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
		<head>
		  <title>Nhie</title>
		  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		  <%= csrf_meta_tags %>
		  <!-- ++++++++++++++ -->
		  <!-- ++++++++++++++ -->
		</head>
	<body class="<%= controller_name %> <%= action_name %>">

	<!-- ++++++//WED NAV BAR\\++++++ -->

<% if logged_in? %>

<nav class="navbar navbar-default navbar-fixed-top nhie-nav" role="navigation">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
    <%= link_to image_tag("main-large-logo_3.png"), root_url, class: 'nav-bar-link main-large-logo' %>
      </div>
      <div class="col-sm-4">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%#= render :partial => 'events_search' %>
      <!-- <form class="navbar-form navbar-right" role="search"> THIS HAS THE -->
        <!-- <div class="form-group"> -->
          <%= form_tag all_search_path, class: 'navbar-form navbar-right form-group form-control'  do %>
            <%= text_field_tag "query", nil, placeholder: '  Search' %>
            <%= submit_tag "Search", class: "btn btn-default search-submit" %>
          <% end %>
          <!-- <input type="text" class="form-control" placeholder="Search"> -->
        <!-- </div> -->
        <!-- <button type="submit" class="btn btn-default">Submit</button> -->
      </form>
    </div><!-- /.navbar-collapse -->
      </div>
    </div>
    
    <!-- Brand and toggle get grouped for better mobile display {:class 'nav-bar-link'} -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->

    <!-- Collect the nav links, forms, and other content for toggling -->
      <!-- <ul class="nav navbar-nav navbar-right"> -->
        <!-- <a href="#">Link</a> -->
      <!-- </ul> -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>
	<!-- ++++++//WED NAV BAR\\++++++ -->
	<nav class="main-nav" id="main-nav">
	  <!-- <a href="#">Events</a> -->
	  <!-- <a href="#">Profile</a> -->
	  <!-- <a href="#">Friends</a> -->
				<% if logged_in? %>
					<div class="sidebar-photo">
						<%= image_tag(current_user.image, size: "200x200") %>
					</div>
					<h1 class="sidebar-name">Howdy, <strong><%=current_user.username %>!</strong></h1>
					<!-- <hr class="sidebar-hr"> -->
					<div class="sidebar-links">
						<%#= link_to("Profile", user_url(current_user)) %>
						<%#= link_to("Events", events_url)%>
						<%#= link_to("Friends", users_url)%>
						<%#= link_to("Log out", logout_path) unless current_page?(login_path) %>

						<%= link_to user_url(current_user) do %>
  						<span class="glyphicon glyphicon-user"> PROFILE</span> 
						<% end %> 
						<%= link_to events_path("Events") do %>
  						<span class="glyphicon glyphicon-list-alt"> EVENTS</span>
						<% end %>
						<%= link_to users_url("Friends") do %>
  						<span class="glyphicon glyphicon-link"> FRIENDS</span> 
						<% end %> 
						<%= link_to logout_path("Log out") do %>
  						<span class="glyphicon glyphicon-off"> LOGOUT</span> 
						<% end %>

						<p class="member-since">Member Since <%= current_user.created_at.strftime("%d %b. %Y") %></p>
					</div>
				<% end %>
	</nav>
		<div class="page-wrap">
		  <% if logged_in? %>
			  <header class="main-header">
			    <!-- <a href="#main-nav" class="open-menu toggle-menu">
			      &#8801;
			    </a> -->
			    <a href="#main-nav" class="open-menu toggle-menu">
			    	<span class="glyphicon glyphicon-chevron-right"></span>
			    </a>
 					<a href="#" class="close-menu toggle-menu">
 						<span class="glyphicon glyphicon-chevron-left"></span>
 					</a>
			    <!-- <a href="#" class="close-menu toggle-menu">
			      &#8801;
			    </a> -->
			    <%#= render :partial => 'events_search' %>
			  </header>
			<% end %>
		  <div class="content">
		      <div class="col-sm-6 col-sm-offset-3">
		        <%= yield %>
		         		<!-- checking for error messages -->
						<% flash.each do |name, msg| %>
						  <% if msg.is_a?(String) %>
						    <%= content_tag :div, msg, :class => "flash_#{name}" %>
						  <% end %>
						<% end %>
		      </div>
		  </div> 
		</div>
	</body>
</html>